cache: pip
dist: xenial
install: pip install .[test]
jobs:
  include:
    - install: pip install .[lint]
      python: 3.7
      script:
        - black --check --verbose *.py deslackify
        - flake8 --exclude=.eggs,build,docs
      stage: lint
language: python
python:
  - 3.7
  - 2.7
script: pytest
stages:
  - lint
  - test
